### ISSUE TITLE
My smart wallet loads continuesly but never completley

### ISSUE THREAD

**Issue by MELCHEZEDEK776** [kenCode-de/smartcoins-wallet#47]
My wallet just loads but but keeos spinning and wont let me send or recieve...? Why?

**Comment by linouxis9** [comment]
Same issue. If I receive a tx, the balance will increase but impossible to see the sender in the transactions list.

**Comment by kenCode-de** [comment]
Right, this is a (98% certainty) connection issue with the full nodes, allowing the wallet to sync up completely. Once we have the new servers online (hopefully before the end of August), these connection issues will be a moot point. This issue is known and is being solved today and in the coming days. No need to upgrade your wallet either, because we have already built-in "WSS Hopping" in Smartcoins Wallet v1.0.5 which will allow you to take advantage of these speed improvements the moment the new servers come online. Thanx guys! Closing this issue for now.
